version: '3'
services:
  client1:
    build: ./Client1
    links:
      - server
    ports:
      - "14022:22"
    volumes:
      - ./Client1:/home
    command: sh /home/AlphaClient.sh
  client2: 
    build: ./Client2
    links:
      - server
    ports:
      - "14023:22"
    volumes:
      - ./Client2:/home
    command: sh /home/AlphaClient.sh
    depends_on:
      - client1
  server:
    build: ./Server
    volumes:
      - ./Server:/home
    ports:
      - "14024:22"
    command: sh /home/AlphaServer.sh
