FROM ubuntu:16.04

RUN apt-get -y update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:admin123' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN apt-get install -y rsyslog && apt-get install -y rsync

EXPOSE 22
CMD rsyslogd & sh /home/AlphaServer.sh & /usr/sbin/sshd -D
